### ISSUE TITLE
Toolbar customization broken by 2170 if defaults are dragged onto the toolbar

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#266]
**Describe**
As of tag 2170, the first version to introduce the Metal visualizer, whether or not it successfully initializes, the toolbar will no longer be configurable if the defaults are dragged onto the toolbar from the customize pane.

**To Reproduce** (delete if not applicable)
1. Right/Ctrl click on the toolbar
2. Click on 'Customize Toolbar'
3. Click and drag the defaults onto the toolbar
4. Toolbar can no longer be altered

**Expected behavior**
Controls should still be removable or addable.

**Version information:***
 - macOS version: 10.13.6
 - Cog version: 2170+

**Additional context**
This bug only affects macOS High Sierra, so it should probably be safe to close it as WONTFIX.

**Comment by kode54** [comment]
This appears to affect Mojave as well. No idea if it affects Catalina or Big Sur, but it doesn't affect Monterey or Ventura beta.

**Comment by waaykool** [comment]
Unable to customize toolbar in Mojave (or Catalina) EXCEPT for dragging in default. Dragging default doesn't break customization, it's just the only action customization will allow.

I can open any versions of Cog PRE-v2170 and customize the toolbar as expected. I can then reopen Cog post-v2170 and toolbar changes which were made in earlier versions are recognized and honored. 

In post-2170, I am unable to add or remove any item from toolbar, except if toolbar is not already set to default. In that case, I am able to drag in defaults - then unable to make any other changes without reverting to Pre-2170. Dragging default into window is not the thing that breaks customization - it's just the only action allowed.

I have just confirmed the same issue appears in Catalina running a Mac Mini (i7).

**Comment by kode54** [comment]
This may be fixed by 7c8a270ed2e9a867003f931cb541a015c9c26c22, which may apparently affect newer SDK versions, which I may have switched to back around 2170? I was still using Xcode 13 around then, but maybe a newer version at that point. I've also since switched to working with Xcode 14 beta on Ventura beta, which seems to be mostly fine for now.

Let me know how 2255-g90b83f8f handles it, once I've uploaded it.

**Comment by kode54** [comment]
This is a bug in the Xcode 13.4, 13.4.1, and 14.0 beta compilers. 13.3.1 is the last version to work properly. 13.3.1 requires Monterey or Big Sur to work.

**Comment by waaykool** [comment]
version 2260 fixes this issue for me.

Confirmed to be working in Catalina and Mojave.

Thanks!

**Comment by kode54** [comment]
Version 2260 was built with Xcode 13.3.1 on macOS Monterey. That is how I have to build it until this issue is resolved by Apple.

Incidentally, the bug has been confirmed to also affect Monterey when built with Xcode 14.0 beta. So this bug continues to be a problem for all stable OS users.

**Comment by waaykool** [comment]
I've discovered that 2260 and after, "Spectrum" can be added to toolbar only by adding the default toolbar. It can't be added by dragging 'spectrum' individually, and its icon remains blank in the customization window. However, the icon will appear normally in the toolbar if default set is dragged in. I can individually drag Spectrum icon out of the toolbar once default set is added, but can only get it back by adding it as part of the whole default toolbar. 

This is a minor issue at this point, since I can get full customization by dragging in default set and customizing from there.

Enclosed screenshot of customization window showing blank "spectrum" icon.
![2266](https://user-images.githubusercontent.com/73963913/173385288-5dd926b7-4a68-48f8-a4fe-f50b5f394746.jpg)
.

**Comment by kode54** [comment]
I can't reproduce this with 2268-g9d558a89 on High Sierra. I don't have Catalina to test.

**Comment by kode54** [comment]
Verified that this issue does occur still with the spectrum button, but only on Mojave and Catalina, not High Sierra or Monterey, and presumably not Big Sur. Doesn't seem to affect Ventura.

**Comment by waaykool** [comment]
I just discovered that in the customize toolbar window, if I put my cursor over the blank space above the "spectrum" text where the Icon should normally appear, and just drag the blank and empty space into the toolbar - as if there _were_ an icon, Spectrum will add normally and show in the toolbar as expected. (see screen capture)

https://user-images.githubusercontent.com/73963913/174115272-a6d6627f-0bd6-4003-854e-8e610beb1f61.mp4

.

**Comment by waaykool** [comment]
All of above issues resolved as of version 2318.

**Comment by kode54** [comment]
Please verify whether this has reoccurred with the web version, and compare with the App Store version. Follow the pinned issue if you are migrating from a non-Sandboxed version.

**Comment by kode54** [comment]
Has anyone noticed this problem still occurring? There are several versions in the current history where I was using Xcode 14 beta 2 for the self distribution version.
